# Generated by Django 3.2.7 on 2021-09-23 14:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('Webfautheque', '0003_auto_20210923_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defaut',
            name='defaut_image',
            field=models.ImageField(blank=True, default='None', upload_to='static/Webfautheque/None/Schema'),
        ),
    ]
