# Generated by Django 3.2.7 on 2021-09-28 11:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('Webfautheque', '0004_alter_defaut_defaut_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experience',
            old_name='experience_actions',
            new_name='experience_descriptif',
        ),
        migrations.RenameField(
            model_name='experience',
            old_name='experience_resultats',
            new_name='experience_remedes',
        ),
        migrations.AlterField(
            model_name='defaut',
            name='defaut_image',
            field=models.ImageField(blank=True, default='None',
                                    upload_to='static/Webfautheque/<bound method CharField.to_python of <django.db.models.fields.CharField>>/Schema'),
        ),
    ]
