# Generated by Django 3.2.7 on 2021-09-28 12:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('Webfautheque', '0005_auto_20210928_1331'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupe',
            old_name='groupes_nom',
            new_name='groupe_nom',
        ),
    ]
