# Generated by Django 3.2.7 on 2021-09-28 12:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('Webfautheque', '0006_rename_groupes_nom_groupe_groupe_nom'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='experience_ift',
            field=models.FileField(default='None', upload_to='static/Webfautheque/ift'),
        ),
        migrations.AlterField(
            model_name='defaut',
            name='defaut_image',
            field=models.ImageField(blank=True, default='None', upload_to='static/Webfautheque/presentation_defauts'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='experience_rapport_anomalie',
            field=models.FileField(default='None', upload_to='static/Webfautheque/rapport_anomalie'),
        ),
    ]
