# Generated by Django 3.2.7 on 2021-09-28 12:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('Webfautheque', '0007_auto_20210928_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='experience_photos',
            field=models.FileField(default='None', upload_to='static/Webfautheque/photos'),
        ),
    ]
