# Generated by Django 4.0.3 on 2022-04-06 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Webfautheque', '0008_alter_experience_experience_photos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classe',
            name='classe_idperso',
            field=models.CharField(max_length=1, verbose_name='Classe'),
        ),
        migrations.AlterField(
            model_name='classe',
            name='classe_nom',
            field=models.CharField(max_length=200, verbose_name='Intitulé'),
        ),
        migrations.AlterField(
            model_name='defaut',
            name='defaut_causes',
            field=models.TextField(max_length=2000, verbose_name='Causes'),
        ),
        migrations.AlterField(
            model_name='defaut',
            name='defaut_description',
            field=models.TextField(max_length=2000, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='defaut',
            name='defaut_idperso',
            field=models.CharField(max_length=4, verbose_name='Defaut'),
        ),
        migrations.AlterField(
            model_name='defaut',
            name='defaut_image',
            field=models.ImageField(blank=True, default='None', upload_to='static/Webfautheque/presentation_defauts', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='defaut',
            name='defaut_info',
            field=models.TextField(max_length=2000, verbose_name='Information'),
        ),
        migrations.AlterField(
            model_name='defaut',
            name='defaut_nom',
            field=models.CharField(max_length=200, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='defaut',
            name='defaut_remedes',
            field=models.TextField(max_length=2000, verbose_name='Remedes'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='experience_auteur',
            field=models.CharField(max_length=200, verbose_name='Auteur'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='experience_descriptif',
            field=models.TextField(default=' ', max_length=2000, verbose_name='descriptif'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='experience_ift',
            field=models.FileField(default='', upload_to='static/Webfautheque/ift', verbose_name='ift'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='experience_numero_article',
            field=models.CharField(max_length=200, verbose_name="numero d'article"),
        ),
        migrations.AlterField(
            model_name='experience',
            name='experience_photos',
            field=models.FileField(default='', upload_to='static/Webfautheque/photos', verbose_name='photo'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='experience_pub_date',
            field=models.DateTimeField(verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='experience_rapport_anomalie',
            field=models.FileField(default='', upload_to='static/Webfautheque/rapport_anomalie', verbose_name='rapport'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='experience_remedes',
            field=models.TextField(default='', max_length=2000, verbose_name='remedes'),
        ),
        migrations.AlterField(
            model_name='groupe',
            name='groupe_idperso',
            field=models.CharField(max_length=4, verbose_name='Groupe'),
        ),
        migrations.AlterField(
            model_name='groupe',
            name='groupe_nom',
            field=models.CharField(max_length=200, verbose_name='Intitulé'),
        ),
        migrations.AlterField(
            model_name='sous_groupe',
            name='sous_groupe_idperso',
            field=models.CharField(max_length=4, verbose_name='Sous groupe'),
        ),
    ]
