# Generated by Django 4.0.3 on 2022-04-08 05:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Webfautheque', '0009_alter_classe_classe_idperso_alter_classe_classe_nom_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='experience_ift',
            field=models.FileField(default=' ', upload_to='static/Webfautheque/ift', verbose_name='ift'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='experience_photos',
            field=models.FileField(default=' ', upload_to='static/Webfautheque/photos', verbose_name='photo'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='experience_pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='experience_rapport_anomalie',
            field=models.FileField(default=' ', upload_to='static/Webfautheque/rapport_anomalie', verbose_name='rapport'),
        ),
    ]
