# Generated by Django 4.0.3 on 2022-04-11 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Webfautheque', '0014_alter_experience_experience_ift_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='experience_ift',
            field=models.FileField(default='None', upload_to='static/Webfautheque/ift', verbose_name='Ift'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='experience_photos',
            field=models.FileField(default='None', upload_to='static/Webfautheque/photos', verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='experience_rapport_anomalie',
            field=models.FileField(default='None', upload_to='static/Webfautheque/rapport_anomalie', verbose_name='rapport anomalie '),
        ),
        migrations.AlterField(
            model_name='sous_groupe',
            name='sous_groupe_nom',
            field=models.CharField(max_length=200, verbose_name='Nom sous groupe'),
        ),
    ]
