# Generated by Django 4.0.3 on 2022-04-12 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Webfautheque', '0015_alter_experience_experience_ift_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='experience_auteur',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Auteur'),
        ),
    ]
