# Generated by Django 4.0.3 on 2022-04-13 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Webfautheque', '0016_alter_experience_experience_auteur'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experience',
            old_name='experience_numero_article',
            new_name='experience_nom_article',
        ),
    ]
