# Generated by Django 4.0.3 on 2022-04-13 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Webfautheque', '0017_rename_experience_numero_article_experience_experience_nom_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='experience_nom_article',
            field=models.CharField(max_length=200, verbose_name="nom de l'article"),
        ),
    ]
