# Generated by Django 4.0.3 on 2022-05-05 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Webfautheque', '0018_alter_experience_experience_nom_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='experience_ift',
            field=models.FilePathField(default='None', path='static/Webfautheque/ift', verbose_name='Ift'),
        ),
    ]
