# Generated by Django 4.0.3 on 2022-05-05 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Webfautheque', '0019_alter_experience_experience_ift'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='experience_ift',
            field=models.FileField(default='None', upload_to='static/Webfautheque/ift', verbose_name='Ift'),
        ),
    ]
