# Generated by Django 4.0.3 on 2022-05-09 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Webfautheque', '0020_alter_experience_experience_ift'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='experience_ift',
            field=models.ImageField(default='None', upload_to='static/Webfautheque/ift', verbose_name='Ift'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='experience_photos',
            field=models.ImageField(default='None', upload_to='static/Webfautheque/photos', verbose_name='Photo'),
        ),
    ]
