# Generated by Django 4.0.3 on 2022-05-10 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Webfautheque', '0021_alter_experience_experience_ift_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='experience_ift_2',
            field=models.ImageField(default='None', upload_to='static/Webfautheque/ift', verbose_name='Ift_é'),
        ),
    ]
