# Generated by Django 4.0.3 on 2022-05-10 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Webfautheque', '0022_experience_experience_ift_2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='experience_ift_2',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='experience_photos',
        ),
        migrations.AddField(
            model_name='experience',
            name='experience_photos_1',
            field=models.ImageField(default='None', upload_to='static/Webfautheque/photos', verbose_name='Photo_1'),
        ),
        migrations.AddField(
            model_name='experience',
            name='experience_photos_2',
            field=models.ImageField(default='None', upload_to='static/Webfautheque/photos', verbose_name='Photo_2'),
        ),
    ]
