# Generated by Django 4.0.3 on 2022-05-30 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Webfautheque', '0024_alter_experience_experience_nom_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defaut',
            name='defaut_idperso',
            field=models.CharField(max_length=4, verbose_name='Code defaut'),
        ),
        migrations.AlterField(
            model_name='defaut',
            name='defaut_nom',
            field=models.CharField(max_length=200, verbose_name='Nom defaut'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='experience_descriptif',
            field=models.TextField(default=' ', max_length=5000, verbose_name='descriptif'),
        ),
        migrations.AlterField(
            model_name='groupe',
            name='groupe_idperso',
            field=models.CharField(max_length=4, verbose_name='Nom du groupe'),
        ),
        migrations.AlterField(
            model_name='groupe',
            name='groupe_nom',
            field=models.CharField(max_length=200, verbose_name='Description '),
        ),
        migrations.AlterField(
            model_name='sous_groupe',
            name='sous_groupe_nom',
            field=models.CharField(max_length=200, verbose_name='Sous groupe'),
        ),
    ]
