# Generated by Django 4.0.3 on 2022-05-31 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Webfautheque', '0025_alter_defaut_defaut_idperso_alter_defaut_defaut_nom_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='experience_photos_1',
            field=models.ImageField(default='None', upload_to='static/Webfautheque/photos', verbose_name='Photo 1'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='experience_photos_2',
            field=models.ImageField(default='None', upload_to='static/Webfautheque/photos', verbose_name='Photo 2'),
        ),
        migrations.AlterField(
            model_name='sous_groupe',
            name='sous_groupe_nom',
            field=models.CharField(max_length=200, verbose_name='Description'),
        ),
    ]
