# Generated by Django 4.0.3 on 2022-06-01 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Webfautheque', '0026_alter_experience_experience_photos_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='experience_rapport_anomalie',
            field=models.CharField(blank=True, default='None', max_length=200, verbose_name='Rapport anomalie'),
        ),
    ]
