# Generated by Django 4.0.3 on 2022-06-02 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Webfautheque', '0027_alter_experience_experience_rapport_anomalie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='experience_rapport_anomalie',
            field=models.FileField(blank=True, default='None', upload_to='static/Webfautheque/rapport_anomalie', verbose_name='Rapport anomalie'),
        ),
    ]
