# Generated by Django 4.0.5 on 2022-06-14 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Webfautheque', '0028_alter_experience_experience_rapport_anomalie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='experience_ift',
            field=models.CharField(blank=True, default='None', max_length=200, verbose_name='Ift'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='experience_rapport_anomalie',
            field=models.CharField(blank=True, default='None', max_length=200, verbose_name='Rapport anomalie'),
        ),
    ]
