# Generated by Django 4.0.5 on 2022-06-22 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Webfautheque', '0029_alter_experience_experience_ift_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classe',
            name='classe_nom',
            field=models.CharField(max_length=2000, verbose_name='Intitulé'),
        ),
        migrations.AlterField(
            model_name='defaut',
            name='defaut_causes',
            field=models.TextField(max_length=20000, verbose_name='Causes'),
        ),
        migrations.AlterField(
            model_name='defaut',
            name='defaut_description',
            field=models.TextField(max_length=20000, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='defaut',
            name='defaut_info',
            field=models.TextField(max_length=20000, verbose_name='Information'),
        ),
        migrations.AlterField(
            model_name='defaut',
            name='defaut_nom',
            field=models.CharField(max_length=2000, verbose_name='Nom defaut'),
        ),
        migrations.AlterField(
            model_name='defaut',
            name='defaut_remedes',
            field=models.TextField(max_length=20000, verbose_name='Remedes'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='experience_auteur',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='Auteur'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='experience_descriptif',
            field=models.TextField(default=' ', max_length=50000, verbose_name='descriptif'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='experience_ift',
            field=models.CharField(blank=True, default='None', max_length=2000, verbose_name='Ift'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='experience_nom_article',
            field=models.CharField(max_length=2000, verbose_name='Code expérience'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='experience_rapport_anomalie',
            field=models.CharField(blank=True, default='None', max_length=2000, verbose_name='Rapport anomalie'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='experience_remedes',
            field=models.TextField(default='', max_length=20000, verbose_name='remedes'),
        ),
        migrations.AlterField(
            model_name='groupe',
            name='groupe_nom',
            field=models.CharField(max_length=2000, verbose_name='Description '),
        ),
        migrations.AlterField(
            model_name='sous_groupe',
            name='sous_groupe_nom',
            field=models.CharField(max_length=2000, verbose_name='Description'),
        ),
    ]
