# Generated by Django 4.0.5 on 2022-06-29 10:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Webfautheque', '0030_alter_classe_classe_nom_alter_defaut_defaut_causes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='defaut',
            name='defaut_modif_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de modification'),
        ),
    ]
