# Generated by Django 4.0.5 on 2022-07-06 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Webfautheque', '0032_alter_defaut_defaut_modif_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='defaut',
            name='defaut_ressource',
            field=models.JSONField(blank=True, default=None, verbose_name='Ressources'),
        ),
    ]
