# Generated by Django 4.0.5 on 2022-07-04 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Webfautheque', '0033_history'),
    ]

    operations = [
        migrations.DeleteModel(
            name='History',
        ),
    ]
