# Generated by Django 4.0.5 on 2022-07-04 10:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Webfautheque', '0034_delete_history'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_modification', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de modification')),
                ('user_modification', models.CharField(max_length=2000, verbose_name='Utilisateur de modification')),
                ('classe_idperso', models.CharField(max_length=1, verbose_name='Classe')),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Webfautheque.classe')),
            ],
        ),
    ]
