# Generated by Django 4.0.5 on 2022-07-06 14:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Webfautheque', '0034_remove_defaut_defaut_ressource'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='experience_document',
            field=models.FileField(default='None', upload_to='static/Webfautheque/documents', verbose_name='Document'),
        ),
        migrations.AddField(
            model_name='experience',
            name='experience_modif_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de modification'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='experience_nom_article',
            field=models.CharField(max_length=2000, verbose_name='numéro article'),
        ),
    ]
