# Generated by Django 4.0.5 on 2022-07-06 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Webfautheque', '0036_remove_experience_experience_modif_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='defaut',
        ),
        migrations.AddField(
            model_name='experience',
            name='defaut',
            field=models.ManyToManyField(blank=True, to='Webfautheque.defaut'),
        ),
    ]
