# Generated by Django 4.0.5 on 2022-07-07 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Webfautheque', '0037_remove_experience_defaut_experience_defaut'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='defaut',
        ),
        migrations.AddField(
            model_name='experience',
            name='defaut',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Webfautheque.defaut'),
            preserve_default=False,
        ),
    ]
