# Generated by Django 4.0.5 on 2022-07-08 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Webfautheque', '0038_remove_experience_defaut_experience_defaut'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='experience_chemin_ift',
            field=models.CharField(default='', max_length=2000, verbose_name='chemin_ift'),
        ),
        migrations.AddField(
            model_name='experience',
            name='experience_chemin_rapport',
            field=models.CharField(default='', max_length=2000, verbose_name='chemin_rapport'),
        ),
        migrations.RemoveField(
            model_name='experience',
            name='defaut',
        ),
        migrations.AddField(
            model_name='experience',
            name='defaut',
            field=models.ManyToManyField(to='Webfautheque.defaut'),
        ),
    ]
